site_name: PD3 Wwise Audio Modding
site_url: https://gamest23.github.io/PD3WwiseAudioModding/

# Website Theme/Colors
theme:
  name: material
  custom_dir: overrides
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
     - navigation.footer
     - navigation.path

# Plugins
plugins:
  - open-in-new-tab

# Icon/emoji Support
markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

# Navigation panels
nav:
  - Home: index.md
  - First Time Setup:
    - Disclaimer: First Time Setup/Disclaimer.md
    - Visual Studio: First Time Setup/Visual Studio.md
    - Unreal Engine: First Time Setup/Unreal Engine.md
    - Wwise: First Time Setup/Wwise.md
    - Post Restart: First Time Setup/Post Restart.md
    - UE Project: First Time Setup/UE Project.md
  - Tips: Tips.md
  - Wwise information: WwiseInfo/WwiseInfo.md
  - RTPC: RTPC/RTPC.md
  - Standard Enemies SFX:
    - Walking: Enemies SFX/Standard/Walking.md
    - Guard Lure Interact: Enemies SFX/Standard/Guard Lure Interact.md
    - Rappel: Enemies SFX/Standard/Rappel.md
    - Sliding: Enemies SFX/Standard/Sliding.md
  - Standard Enemies Voice Lines:
    - All of them: Enemies VFX/Standard/All Standard.md
  - Specials SFX:
    - Bulldozer: Enemies SFX/Specials/Bulldozer.md
    - Cloaker: Enemies SFX/Specials/Cloaker.md
    - Nader: Enemies SFX/Specials/Nader.md
    - Shield: Enemies SFX/Specials/Shield.md
    - Sniper: Enemies SFX/Specials/Sniper.md
    - Techie: Enemies SFX/Specials/Techie.md
    - Zapper (tazer): Enemies SFX/Specials/Zapper.md
  - Specials Voice Lines:
    - Bulldozer: Enemies VFX/Specials/Bulldozer.md
    - Cloaker: Enemies VFX/Specials/Cloaker.md
    - Nader: Enemies VFX/Specials/Nader.md
    - Shield: Enemies VFX/Specials/Shield.md
    - Techie: Enemies VFX/Specials/Techie.md
    - Zapper (tazer): Enemies VFX/Specials/Zapper.md
  - FBI Voice Lines:
    - FBI: Enemies VFX/FBI/FBI.md
  - Enemy Misc.:
    - Dispatch Pager Speech: Enemy Misc/Dispatch.md
    - Radio Dispatcher: Enemy Misc/Guard Radio Small Talk.md
    - First Responder Megaphone: Enemy Misc/Megaphone Guy.md
    - Smalltalk Police: Enemy Misc/Small-Talk Police.md
#  - Shade - Core Heists:
#    - No Rest for the Wicked: Shade/Core Heists/NRFTW.md
#    - Road Rage:
#    - Dirty Ice:
#    - Rock the Cradle:
#    - Under the Surphaze:
#    - Gold and Sharke:
#    - 99 Boxes:
#    - Touch the Sky:
#  - Shade - Side Hustles:
#    - Turbid Station:
#    - Cook Off:
#    - Diamond District:
#    - First World Bank: 
#    - Party Powder:
#    - Shopping Spree:
#  - Shade - The Bad Apple:
#    - Syntax Error:
#    - Boys in Blue:
#    - Houston Breakout:
#    - Fear & Greed:
#  - Shade - Smash & Grab:
#    - Bank Withdrawal:
#    - Search and Seizure:
#  - Shade - Tutorials:
#    - Combat:
#    - Social Stealth:
#    - Crowd Control:
  - Building Sounds:
    - Alarm(s): Building Sounds/Alarm.md
    - Elevator: Building Sounds/Elevator.md
  - Mod Add-ons:
    - Main Menu Music Jukebox Edition: Mod Add-ons/Main Menu Music Jukebox.md
#    - Pause Menu Music:
    - Custom Heist Music: Mod Add-ons/Custom Heist Music.md
  - Misc.:
    - Radio Lure: Misc/Radio Lure.md
    - Phone Hacking Circle: Misc/Phone Hacking Circle.md
    - Main Menu Music Event: Misc/Main Menu Music Event.md
    - Overkill Delivery Drone: Misc/Overkill Delivery Drone.md
    - Player Phone: Misc/Player Phone.md
  - Paking Your Mod:
    - Generate Sound Data: UE Paking/Generate Sound Data.md
    - Folder Sturcture: UE Paking/Folder Structure.md
    - Paking:  UE Paking/Paking.md

# Footer
extra:
  social:
      - icon: simple/github
        link: https://github.com/Gamest23/PD3WwiseAudioModding
      - icon: Icons/mws_logo_white
        link: https://modworkshop.net/user/gamest23
copyright: Copyright &copy; 2026 All rights reserved