site_name: Payday 3 Wwise/Event Audio Modding
site_url: https://gamest23.github.io/PD3WwiseAudioModding/

# Website Theme/Colors
theme:
  name: material
  custom_dir: overrides
  icon: 
    logo: Icons/logo
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
     - navigation.footer
     - navigation.path

# Plugins
plugins:
  - open-in-new-tab
  - search

# Icon/emoji Support
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

# Navigation panels
nav:
  - Home: index.md
  - First Time Setup:
    - Disclaimer: First Time Setup/Disclaimer.md
    - Visual Studio: First Time Setup/Visual Studio.md
    - Unreal Engine: First Time Setup/Unreal Engine.md
    - Wwise: First Time Setup/Wwise.md
    - Post Restart: First Time Setup/Post Restart.md
    - UE Project: First Time Setup/UE Project.md
  - Tips: Tips.md
  - Wwise information: WwiseInfo/WwiseInfo.md
  - Audio Obstruction: Audio Obstruction/Audio Obstruction.md
  - Standard Enemies SFX:
    - Walking: Enemies SFX/Standard/Walking.md
    - Guard Lure Interact: Enemies SFX/Standard/Guard Lure Interact.md
    - Rappel: Enemies SFX/Standard/Rappel.md
    - Sliding: Enemies SFX/Standard/Sliding.md
  - Standard Enemies Voice Lines:
    - Guards & SWAT: Enemies VFX/Standard/Guards & SWAT.md
    - Police: Enemies VFX/Standard/Police.md
    - Smalltalk Police: Enemies VFX/Standard/Small-Talk Police.md
    - Dispatch Pager Speech: Enemies VFX/Standard/Dispatch.md
    - Radio Dispatcher: Enemies VFX/Standard/Guard Radio Small Talk.md
    - First Responder Megaphone: Enemies VFX/Standard/Megaphone Guy.md
  - Specials SFX:
    - Bulldozer: Enemies SFX/Specials/Bulldozer.md
    - Cloaker: Enemies SFX/Specials/Cloaker.md
    - Nader: Enemies SFX/Specials/Nader.md
    - Shield: Enemies SFX/Specials/Shield.md
    - Sniper: Enemies SFX/Specials/Sniper.md
    - Techie: Enemies SFX/Specials/Techie.md
    - Zapper (tazer): Enemies SFX/Specials/Zapper.md
  - Specials Voice Lines:
    - Bulldozer: Enemies VFX/Specials/Bulldozer.md
    - Cloaker: Enemies VFX/Specials/Cloaker.md
    - Nader: Enemies VFX/Specials/Nader.md
    - Shield: Enemies VFX/Specials/Shield.md
    - Techie: Enemies VFX/Specials/Techie.md
    - Drones: Enemies VFX/Specials/Drones.md
    - Zapper (tazer): Enemies VFX/Specials/Zapper.md
  - FBI:
    - FBI Voice Lines: Enemies VFX/FBI/FBI.md
#  - Shade - Core Heists:
#    - No Rest for the Wicked: Shade/Core Heists/NRFTW.md
#    - Road Rage:
#    - Dirty Ice:
#    - Rock the Cradle:
#    - Under the Surphaze:
#    - Gold and Sharke:
#    - 99 Boxes:
#    - Touch the Sky:
#  - Shade - Side Hustles:
#    - Turbid Station:
#    - Cook Off:
#    - Diamond District:
#    - First World Bank: 
#    - Party Powder:
#    - Shopping Spree:
#  - Shade - The Bad Apple:
#    - Syntax Error:
#    - Boys in Blue:
#    - Houston Breakout:
#    - Fear & Greed:
#  - Shade - Smash & Grab:
#    - Bank Withdrawal:
#    - Search and Seizure:
#  - Shade - Tutorials:
#    - Combat:
#    - Social Stealth:
#    - Crowd Control:
  - Building SFX:
    - Alarm(s): Building SFX/Alarm.md
    - Elevator: Building SFX/Elevator.md
    - Night Club Music: Building SFX/Night Club Music.md
  - Player Interactions:
    - Player Phone: Player Interactions/Player Phone.md
    - Elevator Prying: Player Interactions/Elevator Prying.md
    - Radio Lure: Player Interactions/Radio Lure.md
  - Mod Add-ons:
    - Main Menu Music Jukebox Edition: Mod Add-ons/Main Menu Music Jukebox.md
#    - Pause Menu Music:
    - Updated Heist Jukebox: Mod Add-ons/Custom Heist Music.md
  - Misc.:
    - Main Menu Music Event: Misc/Main Menu Music Event.md
    - Phone Hacking Circle: Misc/Phone Hacking Circle.md
    - Overkill Delivery Drone: Misc/Overkill Delivery Drone.md
  - Paking Your Mod:
    - Generate Sound Data: UE Paking/Generate Sound Data.md
    - Folder Sturcture: UE Paking/Folder Structure.md
    - Paking:  UE Paking/Paking.md
  - Paking Your Heist Jukebox Mod:
    - Making it an Add-on: UE Jukebox Paking/Making it an Add-on.md
    - Folder Sturcture: UE Jukebox Paking/Folder Structure.md
    - Paking:  UE Jukebox Paking/Paking.md
  - Paking Your Main Menu Jukebox Mod:
    - Making it an Add-on: UE Main Menu Paking/Making it an Add-on.md
    - Folder Sturcture: UE Main Menu Paking/Folder Structure.md
    - Paking:  UE Main Menu Paking/Paking.md

# Validation rules
validation:
  absolute_links: ignore

# Footer
extra:
  social:
      - icon: simple/github
        link: https://github.com/Gamest23/PD3WwiseAudioModding
      - icon: Icons/mws_logo_white
        link: https://modworkshop.net/user/gamest23
copyright: Copyright &copy; 2026 All rights reserved